### ISSUE TITLE
NGit.Errors.TranslationBundleLoadingException:“Loading of translation bundle failed for [NGit.Internal.JGitText, zh-CN]”

### ISSUE THREAD

**Issue by MrLiu0635** [TetradogOther/NGit#1]
Hello, First, Thanks to your job for a simple port to .netstandard, it's helpful.
When I tried it, Clone gave me a error.

```
NGit.Errors.TranslationBundleLoadingException
  HResult=0x80131500
  Message=Loading of translation bundle failed for [NGit.Internal.JGitText, zh-CN]
  Source=NGit
  StackTrace:
   at NGit.Nls.TranslationBundle.Load(CultureInfo locale)
   at NGit.Nls.GlobalBundleCache.LookupBundle[T](CultureInfo locale)
   at NGit.Nls.NLS.Get[T]()
   at NGit.Api.CloneCommand.Init(URIish u)
   at NGit.Api.CloneCommand.Call()
   at NGit.test.Program.Main(String[] args) in E:\Source\others\another ngit\NGit.test\Program.cs:line 22

```

Progrem.cs:
```
 UsernamePasswordCredentialsProvider provider = new UsernamePasswordCredentialsProvider("***.com", "***");
 Git git2 = Git.CloneRepository().SetBare(false).SetDirectory("F:\\workbench\\test").SetURI("https://***/user-name/***.git").SetCredentialsProvider(provider).Call();
```

**Comment by MrLiu0635** [comment]
I found this:[https://stackoverflow.com/questions/4833959/jgit-egit-loading-of-translation-bundle-failed-en-us](https://stackoverflow.com/questions/4833959/jgit-egit-loading-of-translation-bundle-failed-en-us)

Maybe JGit have resolved this error.
